# Generated by Django 3.0.8 on 2020-08-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
